shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="Login"),
    path('registration/', views.registration, name="Registration"),
    path("home/", views.home, name="Home"),
    path("home/search", views.search, name="Search"),
    path("track-order/", views.track_order, name="TrackingStatus"),
    path("cart/", views.cart, name="Cart"),
    path("product/<slug>/", views.product, name="Product"),
    path("add-to-cart/<slug>/", views.add_to_cart, name="addToCart"),
    path("remove-from-cart/<slug>/", views.remove_from_cart, name="removeFromCart"),
    path("remove-item-from-cart/<slug>/",
         views.remove_single_item_from_cart, name="removeItemFromCart"),
    path("cart/add/<slug>/",
         views.add_single_item_from_cart, name="addItemToCart"),
    path("all-products/<category>/", views.product_list, name="ProductList"),
    path("about-us/", views.about, name="AboutUs"),
    path("checkout/", views.checkout, name="Checkout"),
    path("request/", views.request_product, name="RequestProduct"),
    path("address/", views.address, name="Address"),
    path('logout/', views.logout, name="Logout"),
]

theXpressGrocery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/thexpressgrocery/signup', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.conf import settings

CATEGORY_CHOICES = (
    ('S', 'Staples'),
    ('SB', 'Snacks and Branded Food'),
    ('B', 'Beverages'),
    ('PC', 'Personal Care'),
    ('HC', 'Home Care'),
    ('BC', 'Baby Care')
)


class Product(models.Model):
    #     products_id = models.AutoField
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    product_name = models.CharField(max_length=100)
    mrp = models.FloatField()
    consumer_price = models.FloatField()
    wholesaler_price = models.FloatField()
    desc = models.TextField(max_length=400)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to="shop/images", default="")
    large_image = models.ImageField(upload_to="shop/images", default="")

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse("Product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("addToCart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("removeFromCart", kwargs={
            'slug': self.slug
        })


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.product.product_name}"

    def get_total_mrp(self):
        return round(self.quantity * self.product.mrp, 2)

    def get_total_item_price(self):
        account_type = Profile.objects.filter(user=self.user)[0].account_type
        if account_type == 'P':
            return round(self.quantity * self.product.consumer_price, 2)
        else:
            return round(self.quantity * self.product.wholesaler_price, 2)

    def get_total_you_save(self):
        account_type = Profile.objects.filter(user=self.user)[0].account_type
        if account_type == 'P':
            return round(self.quantity * (self.product.mrp - self.product.consumer_price), 2)
        else:
            return round(self.quantity * (self.product.mrp - self.product.wholesaler_price), 2)


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(Order)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email
    
    def get_billed_amount(self):
        billed = 0
        for item in self.items.all():
            billed += item.get_total_item_price()
        return round(billed, 2)
    
    def get_total_amount(self):
        total = 0
        for item in self.items.all():
            total += item.get_total_item_price()
        total += 25
        return round(total, 2)

    def get_total_savings(self):
        savings = 0
        for item in self.items.all():
            savings += item.get_total_you_save()
        return round(savings, 2)


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=1)
    address_line_1 = models.CharField(max_length=50, default=None, null=True)
    address_line_2 = models.CharField(max_length=50, default=None, null=True)
    city = models.CharField(max_length=50, default=None, null=True)
    state = models.CharField(max_length=50, default=None, null=True)
    zip_code = models.IntegerField(default=1, null=True)

    # address

    def __str__(self):
        return self.user.email

    def get_account_type(self):
        return self.account_type

    def get_address_line_1(self):
        return self.address_line_1

    def get_address_line_2(self):
        return self.address_line_2

    def get_city(self):
        return self.city

    def get_state(self):
        return self.state

    def get_zip_code(self):
        return self.zip_code


class Product_Request(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    request = models.CharField(max_length=500, default=None)
    product_request_time = models.DateTimeField()

    def __str__(self):
        return self.user.email


class Received_Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    total_amount = models.FloatField()
    items = models.TextField(default=None)
    address = models.TextField(default=None)
    receiving_time = models.DateTimeField(default=None)
    delivered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.utils import timezone
from .models import Product, CATEGORY_CHOICES, Profile, Order, Cart, Product_Request, Received_Order
SERVICE_CHARGE = 25.00


def checkAccountType(request):
    account_type = []
    if request.user.is_authenticated == True:
        user_profile = Profile.objects.filter(user=request.user)
        account_type = user_profile[0].account_type
    return account_type


def getAddress(request):
    string_address = ''
    if request.user.is_authenticated == True:
        user_profile = Profile.objects.filter(user=request.user)
        string_address = string_address + user_profile[0].address_line_1 + '\n'
        string_address = string_address + user_profile[0].address_line_2 + '\n'
        string_address = string_address + user_profile[0].city + '\n'
        string_address = string_address + user_profile[0].state + '\n'
        string_address = string_address + str(user_profile[0].zip_code)
    return string_address


def getCartItems(request):
    context = {}
    if Cart.objects.exists:
        cart_items = Cart.objects.filter(user=request.user, ordered=False)
        if cart_items.__len__() > 0:
            order_items = cart_items[0].items.all()
            total_amount = round(cart_items[0].get_total_amount(), 2)
            billed_amount = round(cart_items[0].get_billed_amount(), 2)
            total_saving = round(cart_items[0].get_total_savings(), 2)

            context = {
                'order_items': order_items,
                'total_amount': total_amount,
                'total_saving': total_saving,
                'billed_amount': billed_amount,
                'service_charge': SERVICE_CHARGE
            }
    return context


def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order, created = Order.objects.get_or_create(
        product=product, user=request.user, ordered=False)
    cart_query_set = Cart.objects.filter(user=request.user, ordered=False)
    if cart_query_set.exists():
        cart = cart_query_set[0]
        if cart.items.filter(product__slug=product.slug).exists():
            order.quantity += 1
            order.save()
            messages.success(request, "This item quantity was updated.")
        else:
            cart.items.add(order)
            messages.success(
                request, "This item quantity was addded to the cart.")

    else:
        ordered_date = timezone.now()
        cart = Cart.objects.create(
            user=request.user, ordered_date=ordered_date)
        cart.items.add(order)
        messages.success(request, "This item quantity was addded to the cart.")
    return redirect("Cart")


def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_query_set = Cart.objects.filter(user=request.user, ordered=False)
    cart = cart_query_set[0]
    if cart.items.filter(product__slug=product.slug).exists():
        order = Order.objects.filter(
            product=product, user=request.user, ordered=False)[0]
        cart.items.remove(order)
        order.delete()
        messages.success(request, "This item  was removed from the cart.")

    return redirect('Cart')


def remove_single_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_query_set = Cart.objects.filter(user=request.user, ordered=False)
    if cart_query_set.exists():
        cart = cart_query_set[0]
        if cart.items.filter(product__slug=product.slug).exists():
            order = Order.objects.filter(
                product=product, user=request.user, ordered=False)[0]
            order.quantity -= 1
            order.save()
            if order.quantity == 0:
                cart.items.remove(order)
                order.delete()
                messages.success(request, "This item was removed.")
                return redirect('Cart')

            messages.success(request, "This item quantity was updated.")
            return redirect('Cart')

        return redirect('Cart')


def add_single_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_query_set = Cart.objects.filter(user=request.user, ordered=False)
    if cart_query_set.exists():
        cart = cart_query_set[0]
        if cart.items.filter(product__slug=product.slug).exists():
            order = Order.objects.filter(
                product=product, user=request.user, ordered=False)[0]
            order.quantity += 1
            order.save()
            messages.success(request, "This item quantity was updated.")
            return redirect('Cart')

        return redirect('Cart')


def index(request):
    if request.method == 'POST':
        login_email = request.POST.get('login-email')
        login_password = request.POST.get('login-password')
        user = authenticate(username=login_email, password=login_password)

        if user is not None:
            login(request, user)
            return redirect('Home')
        else:
            messages.error(request=request,
                           message="Invalid Credentials! Please try again.")
            return redirect('Login')

    return render(request, 'index.html')


def registration(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        # email - logic goes here!!####################
        account_type = request.POST.get('account-type')
        password = request.POST.get('password')
        re_password = request.POST.get('re-password')

        if password != re_password:
            messages.error(
                request=request, message="Passwords didn't match! Login to access the website.")
            return redirect('Registration')
        else:

            user = User.objects.create_user(username=email, email=email, password=password,
                                            first_name=fname, last_name=lname)
            user.save()

            user_profile = Profile.objects.create(user=user)
            user_profile.account_type = account_type
            user_profile.save()

            messages.success(
                request=request, message="Successfully Registered!")
            return redirect('Login')

    return render(request, 'registration.html')


def home(request):
    all_products = []
    for category in CATEGORY_CHOICES:
        product = Product.objects.filter(category=category[0])[:10]
        all_products.append([product, category[1]])

    account_type = checkAccountType(request)

    context = {
        'all_products': all_products,
        'account_type': account_type
    }

    return render(request, 'home.html', context)


def search(request):
    query = request.GET.get('query')

    if len(query) > 70:
        products = []
    else:
        words = query.split()
        products = Product.objects.filter(product_name__icontains=query)
        for word in words:
            product = Product.objects.filter(product_name__icontains=word)
            products = products.union(product)

        if products.__len__() < 1:
            for category_items in CATEGORY_CHOICES:
                category = category_items[1].lower()
                if category == query.lower():
                    product = Product.objects.filter(
                        category=category_items[0])
                    products = products.union(product)

    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    account_type = checkAccountType(request)

    context = {
        'page_obj': page_obj,
        'query': query,
        'account_type': account_type
    }
    return render(request, 'search.html', context=context)


def track_order(request):
    total_amount = 0
    items = 0
    receiving_time = 0
    delivered = True
    if request.user.is_authenticated == True:
        received_order = Received_Order.objects.filter(user=request.user)
        if received_order.__len__() > 0:
            length = received_order.__len__()
            total_amount = received_order[length-1].total_amount
            items = received_order[length-1].items
            receiving_time = received_order[length-1].receiving_time
            delivered = received_order[length-1].delivered
        context = {
            'total_amount': total_amount,
            'items': items,
            'receiving_time': receiving_time,
            'delivered': delivered
        }
    return render(request, 'track-order.html', context=context)


def cart(request):
    if request.user.is_authenticated == True:
        context = getCartItems(request=request)
        if context.__len__ == 0:
            return render(request, 'cart.html')
    else:
        return render(request, 'cart.html')
    return render(request, 'cart.html', context=context)


def product(request, slug):
    product = Product.objects.filter(slug=slug)
    other_products = Product.objects.filter(
        category=product[0].category).exclude(slug=slug)[:4]

    account_type = checkAccountType(request)

    if account_type == 'P':
        you_save = round(product[0].mrp - product[0].consumer_price, 2)
    else:
        you_save = round(product[0].mrp - product[0].wholesaler_price, 2)

    context = {
        'product': product[0],
        'other_products': other_products,
        'account_type': account_type,
        'you_save': you_save
    }
    return render(request, 'product-view.html', context)

shop/templates/about-us.html
{% extends 'temp_header.html'%}
{% load static %}
{% block title %} The Xpress Grocery {% endblock %}

{% block body %}
<!-- CONTENT-->
<section class="text-gray-700 body-font">
    <div class="container flex flex-wrap px-5 py-24 mx-auto items-center">
        <div class="md:w-1/2 md:pr-12 md:py-8 md:border-r md:border-b-0 mb-10 md:mb-0 pb-10 border-b border-gray-300">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">About Us</h1>
            <p class="leading-relaxed text-base">We have a wholesale shop running in sakchi since 1980 and now we offer
                our services online as well. We have brought this online platform for the saftey of consumers and
                retailers in this pandemic.
                Order online, stay home, stay safe.</p>
            <br>
            <p class="leading-relaxed text-base">Our Service provides the prices as low as wholesale price for both the
                consumers and retailers and we believe in express service.</p>
            <br>
            <p class="leading-relaxed text-base">Do visit the shop using the link provided below or checkout what we
                provide using the references provided in the 'What we provide' section.</p>
            <a href="/home"class="text-orange-500 inline-flex items-center mt-4 cursor-pointer">Goto Shop
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
            </a>
        </div>
        <div class="flex flex-col md:w-1/2 md:pl-12">
            <h2 class="title-font font-medium text-gray-800 tracking-widest text-md mb-3">What we provide</h2>
            <nav class="flex flex-wrap list-none flex-col">
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="/all-products/Staples" class="text-gray-600 hover:text-orange-600">Staples</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="/all-products/Snacks and Branded Food" class="text-gray-600 hover:text-orange-600">Snacks
                        and
                        Branded Food</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="/all-products/Beverages" class="text-gray-600 hover:text-orange-600">Beverages</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="/all-products/Personal Care" class="text-gray-600 hover:text-orange-600">Personal Care</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="/all-products/Home Care" class="text-gray-600 hover:text-orange-600">Home Care</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="/all-products/Baby Care" class="text-gray-600 hover:text-orange-600">Baby Care</a>
                </li>
            </nav>
        </div>
    </div>
</section>
{% endblock %}

shop/templates/address.html
{% extends 'temp_header.html'%}
{% load static %}
{% block title %} The Xpress Grocery {% endblock %}

{% block body %}
{% if user.is_authenticated %}
<!-- Option to enter address -->
<section class="">
    <h1 class="text-xl text-black traking-wide block font-bold p-2 m-2 text-center pt-12 px-4 ">Enter Your
        Address</h1>
    <div class="flex justify-center items-center pt-4 px-4">
        <form action="/address/" method="POST" class="w-full max-w-lg border-t-2 pt-6">
            {% csrf_token%}
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="address-line-1">
                        Address line - 1
                    </label>
                    <input
                        class="appearance-none block w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-orange-500"
                        id="address-line-1" name="address-line-1" type="text"
                        pattern="([a-zA-Z0-9]| |.|,|-|/|\\|@|#|\$|%|&)+" maxlength="50" required>
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="address-line-2">
                        Address line - 2
                    </label>
                    <input
                        class="appearance-none block w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-orange-500"
                        id="address-line-2" name="address-line-2" pattern="([a-zA-Z0-9]| |.|,|-|/|\\|@|#|\$|%|&)+"
                        maxlength="50" type="text" required>
                </div>
            </div>

            <div class="flex flex-wrap -mx-3 mb-2">
                <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="city">
                        City
                    </label>
                    <input
                        class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                        id="city" name="city" type="text" pattern="[A-Za-z]+" maxlength="50" required>
                </div>
                <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-state">
                        State
                    </label>
                    <div class="relative">
                        <select
                            class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                            id="state" name="state">
                            <option value="Jamshedpur">Jamshedpur</option>
                        </select>
                        <div
                            class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                            </svg>
                        </div>
                    </div>
                </div>
                <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="zip">
                        Zip
                    </label>
                    <input
                        class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                        id="zip" name="zip" type="tel" pattern="[0-9]{6}" required>
                </div>
            </div>

            <div class="flex flex-wrap -mx-3 mt-12 justify-center">
                <button type="submit"
                    class="flex text-white bg-orange-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-orange-400 active:bg-orange-600 rounded text-lg">Save</button>
            </div>
        </form>
    </div>
</section>
{% else %}
<!-- Not an authenticated user -->
<div class="section pt-32 flex flex-col items-center text-center h-screen bg-gray-200 m-1 md:m-4 border-2 rounded">
    <p class="font-bold text-3xl">Please login to access this feature.</p>
    <svg width="120" height="120" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M3 3H5L5.4 5M7 13H17L21 5H5.4M7 13L5.4 5M7 13L4.70711 15.2929C4.07714 15.9229 4.52331 17 5.41421 17H17M17 17C15.8954 17 15 17.8954 15 19C15 20.1046 15.8954 21 17 21C18.1046 21 19 20.1046 19 19C19 17.8954 18.1046 17 17 17ZM9 19C9 20.1046 8.10457 21 7 21C5.89543 21 5 20.1046 5 19C5 17.8954 5.89543 17 7 17C8.10457 17 9 17.8954 9 19Z"
            stroke="#ed8936" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
    <a href="/"
        class="flex text-white bg-orange-500 border-0 mx-auto mt-4 py-2 px-6 focus:outline-none hover:bg-orange-400 active:bg-orange-600 rounded">Login</a>
</div>
{% endif%}
{% endblock %}

shop/templates/product-view.html
<!-- Image size 400x400 -->
{% extends 'temp_basic.html'%}
{% load static %}

{% block title %}
{{product.product_name}} - The Xpress Grocery
{% endblock %}

<!-- {% block css %}{% endblock %} -->

{% block body %}
<!--Product Details-->
<section class="text-black body-font overflow-hidden">
    <div class="container px-4 py-10 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="/media/{{product.large_image}}">

            <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">

                <h2 class="text-sm title-font text-gray-500 tracking-widest">{{product.get_category_display}}</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{product.product_name}}</h1>
                <div class="flex flex-col items-baseline m-2 py-2">
                    <span class="title-font font-medium text-md text-gray-900 mx-2">MRP : <span
                            class="line-through">&#8377 {{product.mrp}}</span>
                    </span>

                    {% if user.is_authenticated %}
                    {% if account_type == "P" %}
                    <div class="flex flex-row flex-wrap items-baseline">
                        <span class="title-font font-medium text-3xl text-gray-900 mx-2">Price : &#8377
                            {{product.consumer_price}}</span>

                        <span class="title-font font-medium text-sm text-gray-900 mx-2">(You Save : &#8377
                            {{you_save}})</span>
                    </div>
                    {% else %}
                    <div class="flex flex-row flex-wrap items-baseline">
                        <span class="title-font font-medium text-3xl text-gray-900 mx-2">Price : &#8377
                            {{product.wholesaler_price}}</span>

                        <span class="title-font font-medium text-sm text-gray-900 mx-2">(You Save : &#8377
                            {{you_save}})</span>
                    </div>
                    {% endif %}
                    {% else %}
                    <span class="title-font font-medium text-md text-gray-900 mx-2">MRP : <span
                            class="line-through"></span>
                        &#8377 ###.##</span>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                <div class="flex mt-6 items-center pb-5 mb-5">
                    <a href="{{product.get_add_to_cart_url}}"
                        class="flex text-white bg-orange-500 border-0 mx-auto py-2 px-6 focus:outline-none hover:bg-orange-400 active:bg-orange-600 rounded">Add
                        to Cart
                    </a>
                </div>
                {% endif %}
                <p class="text-gray-900 text-md title-font font-medium leading-relaxed m-2 py-4 border-t-2 border-b-2">
                    <span class="font-bold">Description </span>: {{product.desc}}</p>

            </div>
        </div>
    </div>
</section>
<hr>

<!-- Specific Categories -->
<section class="text-black body-font">
    <div class="container px-5 py-2 mx-auto">
        <h1 class="text-base text-xl tracking-widest title-font p-4 m-1 mt-8"><a class="hover:text-orange-500"
                href="/all-products/{{product.get_category_display}}">Other
                Products from
                {{product.get_category_display}} ></a>
        </h1>
        <div class="flex flex-wrap -m-4 mb-2">

            {% for item in other_products%}
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full shadow-xl rounded-md cursor-pointer">
                <a href="{{item.get_absolute_url}}" class="block relative h-48 rounded overflow-hidden shadow-md">
                    <img alt="ecommerce" class="object-cover object-center w-full h-full block"
                        src="/media/{{item.image}}">
                </a>
                <div class="mt-2 p-2">
                    <a href="{{item.get_absolute_url}}" class="hover:text-orange-500">
                        <p class="title-font text-lg font-medium truncate">{{item.product_name}}</p>
                    </a>
                    <p class="mt-1 text-sm">MRP : <span class="line-through"> &#8377 {{item.mrp}}</span></p>
                    {% if user.is_authenticated %}
                    {% if account_type == "P" %}
                    <p class="text-md">Price :<span class="font-bold"> &#8377 {{item.consumer_price}}</span>
                    </p>
                    {% else %}
                    <p class="text-md">Price :<span class="font-bold"> &#8377 {{item.wholesaler_price}}</span>
                    </p>
                    {% endif %}
                    {% else %}
                    <p class="text-md">Price :<span class="font-bold"> &#8377 ###.##</span>
                    </p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <hr>
    </div>
</section>
{% endblock %}